# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Trader Binance(Python)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    container: lwinmgmg/poetry:3.11.8-1.8.0
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
    - name: Installation
      run: poetry install
    - name: Black Formatter
      run: poetry run black .
    - name: Flake8 Linter
      run: poetry run flake8
    - name: Pylint Linter
      run: poetry run pylint src/trader

  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    container: lwinmgmg/poetry:3.11.8-1.8.0
    services:
      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
    - name: Copying config
      run: cp .env.example .env
    - name: Installation
      run: poetry install
    - name: Testing
      run: poetry run coverage run -m pytest
    - name: Coverage Report
      run: poetry run coverage report -m